apiVersion: cluster.gravitational.io/v2
kind: Cluster
baseImage: gravity:6.1.11
metadata:
 name: cluster-image
 resourceVersion: 0.0.2
hooks:
  install:
    job: file://install.yaml
  update:
    job: file://upgrade.yaml
