apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    asd.:53 {
      reload
      errors
      health
      prometheus :9153
      cache 30

        \ loop
      reload
      loadbalance
      hosts { 
        fallthrough
      }
      kubernetes
        cluster.local in-addr.arpa ip6.arpa {
        pods verified
        fallthrough in-addr.arpa
        ip6.arpa
      }
      forward . 169.254.169.254 {
        policy sequential
        health_check
        0
      }
    }
