apiVersion: apps/v1
kind: Deployment
metadata:
  name: sidecar
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sidecar
  template:
    metadata:
      labels:
        app: sidecar
    spec:
      containers:
      - image: localhost:5000/service:0.0.1
        name: service
        imagePullPolicy: Always
      - image: localhost:5000/sidecar:0.0.1
        name: sidecar
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sidecar
  labels:
    app: sidecar
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: sidecar
